### ISSUE TITLE
Add Dark Theme

### ISSUE THREAD

**Issue by Maririri** [JetBrains/ij-perf-report-aggregator#93]
Please add the Dark theme to the dashboard :) 

Right now it's the only service that I have with the light theme and it stands out

**Comment by MaXal** [comment]
You can use a browser plugin or Arc browser with Boost to have dark mode:)
<img width="2141" alt="image" src="https://github.com/JetBrains/ij-perf-report-aggregator/assets/266747/60325965-9c2b-4b86-8928-64cc02220daf">

**Comment by MaXal** [comment]
We added a proper dark mode:)
<img width="2174" alt="image" src="https://github.com/user-attachments/assets/3ba0ee7a-ee18-44bf-a238-184f7602eb71">
